version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=temperature_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
    networks:
      - my_network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    external:
      name: temperature-feed_my_network