# Generated by Django 3.2.25 on 2024-04-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperaturereading',
            old_name='value',
            new_name='temperature',
        ),
        migrations.AlterField(
            model_name='temperaturereading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
