# Generated by Django 3.2 on 2024-04-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0002_auto_20240426_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperaturereading',
            old_name='temperature',
            new_name='value',
        ),
    ]
